services:
  laserweb:
    image: mkuf/laserweb:latest
    container_name: laserweb
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./config:/config
      - ./gcode:/gcode
      - /dev:/dev
    ports:
      - "80:80"  
    networks:
      - web
  lw-comm-server:
    image: ./lw.comm-server   
    container_name: lw-comm-server
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /dev:/dev                 
    ports:
      - "8001:8000"               
    networks:
      - web

  # lcd-display:
  #   build: ./IPLaserCNC
  #   container_name: lcd-hostname-ip
  #   restart: unless-stopped
  #   privileged: true

  #   # I2C
  #   devices:
  #     - "/dev/i2c-1:/dev/i2c-1"
  
  #   # Use host network to get host's IP address
  #   network_mode: "host"
    
  #   # Environment variables
  #   environment:
  #     - CONFIG_FILE=/app/config_board.yaml
    
  #   # Health check
  #   healthcheck:
  #     test: ["CMD", "python", "-c", "import socket; socket.gethostname()"]
  #     interval: 30s
  #     timeout: 3s
  #     retries: 3
  #     start_period: 5s
    
  #   # Logging configuration
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
    
  #   # Keep container running
  #   tty: true
  #   stdin_open: true
  
  # mjpg-streamer:
  #   restart: always
  #   image: patsoffice/mjpg-streamer
  #   devices:
  #     - /dev/video0
  #   ports:
  #     - 8081:8080
  #   environment:
  #     - MJPEG_STREAMER_INPUT="-y -n -r 640x480 -f 15 -r 90"
  #   networks:
  #     - web


networks:
  web:
    driver: bridge