# ================================
# List of Docker images to check
# Format:
# IMAGE_NAME|GIT_URL|TAG
# TAG can be omitted (default: latest)
# ================================

# LaserWeb - Web interface for Laser CNC control
mkuf/laserweb|https://github.com/LaserWeb/LaserWeb4.git|latest

# Nginx - Reverse proxy for web interface
nginx|https://github.com/nginx/nginx.git|latest

# mjpg-streamer - Webcam streaming (optional)
patsoffice/mjpg-streamer|https://github.com/jacksonliam/mjpg-streamer.git|latest

# ScaleTail - VPN
tailscale/tailscale|https://github.com/tailscale-dev/ScaleTail.git|latest

